### ISSUE TITLE
Local constants seen as global constants resulting in a duplicate symbols error

### ISSUE THREAD

**Issue by nic0mic** [mParticle/mparticle-apple-sdk#101]
Hello,

Following this issue, I can't reopen as I'm not the one who closed it:
https://github.com/mParticle/mparticle-apple-sdk/issues/100

The fix didn't work for us. There are 2 `MPIAdobe.m` files and we are still using the previous(?) one.😅
**[Not updated:](https://github.com/mparticle-integrations/mparticle-apple-integration-adobe/blob/7.12.7/mParticle-Adobe/MPIAdobe.m)** `mParticle-Adobe/MPIAdobe.m`
**[Updated:](https://github.com/mparticle-integrations/mparticle-apple-integration-adobe/blob/7.12.7/mParticle-Adobe-Media/MPIAdobe.m)** `mParticle-Adobe-Media/MPIAdobe.m`, in **Media** directory

We are still using Adobe kit without the Media dependency (ie via `pod 'mParticle-Adobe/Adobe')`
We got other issues with the `Media` dependency because we already had the `VideoHeartbeatLibrary` SDK added manually in our project. But this is another story ;)

I hope it is good for you to update the other file or let me know. 
Thanks

**Comment by BrandonStalnaker** [comment]
Sorry for the confusion. I just released 7.12.8 for the media-less integration. I'll wait to hear back from you before closing the issue.

**Comment by nic0mic** [comment]
@BrandonStalnaker No worries :)
**It is working** if I use the direct link to the repo, eg:
`    pod 'mParticle-Adobe/Adobe', :git => 'git@github.com:mparticle-integrations/mparticle-apple-integration-adobe.git', :tag => '7.12.8'`

Could you add the new [Cocoapods spec](https://github.com/CocoaPods/Specs/tree/master/Specs/0/1/b/mParticle-Adobe)? Or it will be done automatically when merged?
Thank you!

**Comment by nic0mic** [comment]
@BrandonStalnaker Hello,
I was waiting for the new `7.13.0` mParticle release.

Unfortunately, I can not update to this one because different Kits still rely on mParticle `7.12.*`

Example: [Kochava](https://github.com/mparticle-integrations/mparticle-apple-integration-kochava/blob/master/mParticle-Kochava.podspec), Adobe, Apptentive
In their pod specs, their version number has been bumped to `7.13.0` but they still have a dependency on mParticle 7.12.*

`s.ios.dependency 'mParticle-Apple-SDK/mParticle', '~> 7.12.0'`
instead of
`s.ios.dependency 'mParticle-Apple-SDK/mParticle', '~> 7.12'` like [UrbanAirship Kit](https://github.com/mparticle-integrations/mparticle-apple-integration-urbanairship/blob/master/mParticle-UrbanAirship.podspec)

Is it an error or do these kits still need mParticle 7.12 and so we can not update to mParticle 7.13?

**Comment by BrandonStalnaker** [comment]
@nic0mic Sorry about the confusion. This is an an issue in our automated release script that we're fixing now.

**Comment by nic0mic** [comment]
> @nic0mic Sorry about the confusion. This is an an issue in our automated release script that we're fixing now.

Thanks for the reply, I'll wait the fix 👍

**Comment by BrandonStalnaker** [comment]
@nic0mic You should be good with 7.14

**Comment by nic0mic** [comment]
> @nic0mic You should be good with 7.14

Everything is working! Perfect! I close the issue.
Thank you again :)
