### ISSUE TITLE
How-to know which kits are enabled and/or should be initialized?

### ISSUE THREAD

**Issue by nic0mic** [mParticle/mparticle-apple-sdk#111]
Hello,

Is there a way to know in advance which kits are enabled in the dashbard and should be initialized with the mParticle SDK?

- The `onKitsInitiliazed` method is called **before** our kits are really initialized and active.
- The `kitInstance(..) { }` method is called correctly after the kit is initialized and active **but** if the kit is enabled on mParticle dashboard. Otherwise the completion block is never called.
- `isActive` and `kitInstance` are not set before the kit is initialized correctly.

We want to wait for a kit initilization but only if this kit was added and enabled on the dashboard. How can we do that?
Another solution will be to have the `onKitsInitiliazed` block called only after all the kits are initiliazed and active.

Thank you,

**Comment by BrandonStalnaker** [comment]
You could listen to the `mParticleKitDidBecomeActiveNotification` which is called in `start` right after the kit sdk is initialized. The userInfo within that notification contains the kit code which you can use to identify the integration.

**Comment by nic0mic** [comment]
Hey! Thank you for the reply.
I'm not certain the notification would work as the problem is to be able to know which kits are going to be initialized/enabled. ie. enabled on the dashboard.
and the `kitInstance(..) { }` is not called if the kit is disabled on the dashboard
eg.
```
if kit A enabled on the dashboard
  wait for the kit A initialization
else
  continue other stuff
```
Anyway, this question is now outdated and maybe it is not relevant anymore, I'm not aware of the latest SDK updates.
Thank you!
