### ISSUE TITLE
Inclusion of non modular headers

### ISSUE THREAD

**Issue by KieranLafferty** [mParticle/mparticle-apple-sdk#123]
The library is incompatible if any other pod dependency includes a dep on sqlite 

I created a PR to fix this about 4months ago here https://github.com/mParticle/mparticle-apple-sdk/pull/116

please merge this currently I have to build off of my fork meaning we're always out of date on the SDK and it's a pain to update to newer versions

**Comment by BrandonStalnaker** [comment]
Closed with [merge](https://github.com/mParticle/mparticle-apple-sdk/pull/116)
