### ISSUE TITLE
Support for Swift Package Manager in the kit integrations

### ISSUE THREAD

**Issue by majcher33** [mParticle/mparticle-apple-sdk#125]
Currently the mParticle Apple SDK supports integration via SPM, but the kit integrations only support Cocoapods and Carthage.  Are there any plans to support SPM?  This would be helpful as I'm trying to move everything to SPM and would prefer not to juggle multiple dependency managers.

Thanks for taking a look!

**Comment by Ded77** [comment]
I have the same problem. `mParticle` and `Adjust` was included in my project with SPM. Now, I need the `mParticle-Adjust` integration which does not support SPM. So, I need to all convert with CocoaPods now. Boring :/ 

Thanks !

**Comment by jarod2d** [comment]
Would love to see SPM support for the [Optimizely integration](https://github.com/mparticle-integrations/mparticle-apple-integration-optimizely) as it's one of the last dependencies we have that's keeping us from migrating away from Cocoapods. Thank you 😄

**Comment by julioceballos4** [comment]
@willpassidomo Hello & thank you for adding SPM support. I'm running into an issue using some of the MP components such as `MPKitAppboy` & `MPKitOptimizely`. They require their corresponding mParticle import. When added I get errors such as  `Could not build Objective-C module 'mParticle_Appboy'`. 

Is there a way to overcome this?

**Comment by tony3298** [comment]
@willpassidomo Are there any plans to add the Google-Analytics-Firebase kit to SPM? We're currently using that and the Adobe kit, and I see there is package support for Adobe but not for Firebase. Would be super helpful so that we can potentially get off Cocoapods!
