### ISSUE TITLE
Support simulator builds for Apple Silicon in mParticle-Appboy

### ISSUE THREAD

**Issue by tiwoc** [mParticle/mparticle-apple-sdk#126]
For making simulator builds of apps that include the Appboy/Braze SDK on Apple Silicon (M1) computers, it is necessary to upgrade the `Appboy-iOS-SDK` pod to version 4.x (see https://github.com/Appboy/appboy-ios-sdk/issues/270). The latest release of the `mParticle-Appboy` pod, however, pins the version of `Appboy-iOS-SDK` to 3.x.

To make this work, please update the [podspec](https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/blob/master/mParticle-Appboy.podspec) accordingly. You might need to bump the version of `Appboy-tvOS-SDK`, too.

**Comment by alexs-mparticle** [comment]
@tiwoc Thanks for bringing this up. We're currently investigating upgrade options for this kit. I'll pass it along to our team and we'll see what's involved with adding it to an upcoming release.

**Comment by tiwoc** [comment]
Fixed in [mParticle-Appboy 8.0.11](https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/releases/tag/8.0.11).
