### ISSUE TITLE
Crash spike

### ISSUE THREAD

**Issue by dcacenabes** [mParticle/mparticle-apple-sdk#135]
All of a sudden we've had a spike of crashes in our app.
We are using version 8.3.1 of the SDK.

MPConnector.m:264:25
-[MPConnector responseFromPostRequestToURL:message:serializedParams:]

We are seeing this crash when the app is coming to foreground.

<img width="684" alt="Screenshot 2021-10-01 at 15 56 07" src="https://user-images.githubusercontent.com/3796899/135632271-e48c8f1c-3134-4794-ad20-ed225db74038.png">

**Comment by BrandonStalnaker** [comment]
Hi @dcacenabes ,

I've spent some time looking at the code referenced in our MPConnector and didn't find an obvious culprit. Something we have noticed when using semaphores is that sometimes a crash unrelated to mparticle can occur while a semaphore wait is on the stack and only the semaphore thread is caught by the stack trace.

To help determine if there is an issue we would appreciate any additional information you might have about the crash. A full stack trace and/or information like trends in iOS version from user's experiencing crashes could be very helpful. I'd also recommend updating to the latest version of our sdk to avoid a multitude of issues we've solved in the meantime.

If you have any sensitive but possibly helpful information you'd like to provide please contact us directly through the csm working with your organization. They may also have records on clients experiencing similar issues and be able to provide a quicker solution.

Thank you for opening this and have great day.

**Comment by BrandonStalnaker** [comment]
This issue was brought internally to Zsupport where we were able to confirm it matched a similar issue that was solved previously. Update to at least version 8.3.3 and this will no longer be able to occur.

https://github.com/mParticle/mparticle-apple-sdk/commit/c747b2b2289ca629f396d3e2d13f8e6005c5439b
