### ISSUE TITLE
mParticle-Appsflyer Integration Xcode13 Build Issue

### ISSUE THREAD

**Issue by coolioxlr** [mParticle/mparticle-apple-sdk#139]
Hi, I am using mParticle-Appsflyer SPM Integration. We are able to build in AppCenter when using Xcode 12. But using Xcode13 in AppCenter we are getting the following issue.

`/Applications/Xcode_13.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.0.sdk/Developer/Library/Frameworks -fmodule-map-file\=/Users/runner/Library/Developer/Xcode/DerivedData/WinkRe-figjxhnbwetjbmdiujgusfybryua/Build/Intermediates.noindex/ArchiveIntermediates/WinkRe/IntermediateBuildFilesPath/GeneratedModuleMaps-iphoneos/mParticle-Apple-SDK.modulemap -DXcode -MMD -MT dependencies -MF /Users/runner/Library/Developer/Xcode/DerivedData/WinkRe-figjxhnbwetjbmdiujgusfybryua/Build/Intermediates.noindex/ArchiveIntermediates/WinkRe/IntermediateBuildFilesPath/mParticle-AppsFlyer.build/Release-iphoneos/mParticle-AppsFlyer.build/Objects-normal/arm64/MPKitAppsFlyer.d --serialize-diagnostics /Users/runner/Library/Developer/Xcode/DerivedData/WinkRe-figjxhnbwetjbmdiujgusfybryua/Build/Intermediates.noindex/ArchiveIntermediates/WinkRe/IntermediateBuildFilesPath/mParticle-AppsFlyer.build/Release-iphoneos/mParticle-AppsFlyer.build/Objects-normal/arm64/MPKitAppsFlyer.dia -c /Users/runner/Library/Developer/Xcode/DerivedData/WinkRe-figjxhnbwetjbmdiujgusfybryua/SourcePackages/checkouts/mparticle-apple-integration-appsflyer/Sources/mParticle-AppsFlyer/MPKitAppsFlyer.m -o /Users/runner/Library/Developer/Xcode/DerivedData/WinkRe-figjxhnbwetjbmdiujgusfybryua/Build/Intermediates.noindex/ArchiveIntermediates/WinkRe/IntermediateBuildFilesPath/mParticle-AppsFlyer.build/Release-iphoneos/mParticle-AppsFlyer.build/Objects-normal/arm64/MPKitAppsFlyer.o
/Users/runner/Library/Developer/Xcode/DerivedData/WinkRe-figjxhnbwetjbmdiujgusfybryua/SourcePackages/checkouts/mparticle-apple-integration-appsflyer/Sources/mParticle-AppsFlyer/MPKitAppsFlyer.m:5:9: fatal error: 'AppsFlyerLib.h' file not found
#import "AppsFlyerLib.h"`

`CompileC /Users/runner/Library/Developer/Xcode/DerivedData/WinkRe-figjxhnbwetjbmdiujgusfybryua/Build/Intermediates.noindex/ArchiveIntermediates/WinkRe/IntermediateBuildFilesPath/mParticle-AppsFlyer.build/Release-iphoneos/mParticle-AppsFlyer.build/Objects-normal/armv7/MPKitAppsFlyer.o /Users/runner/Library/Developer/Xcode/DerivedData/WinkRe-figjxhnbwetjbmdiujgusfybryua/SourcePackages/checkouts/mparticle-apple-integration-appsflyer/Sources/mParticle-AppsFlyer/MPKitAppsFlyer.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'mParticle-AppsFlyer' from project 'mParticle-AppsFlyer')`

@peterjenkins

**Comment by einsteinx2** [comment]
@coolioxlr Thanks for submitting this issue, I'll be looking into this today and will get back to you as soon as I have more info.

**Comment by coolioxlr** [comment]
> @coolioxlr Thanks for submitting this issue, I'll be looking into this today and will get back to you as soon as I have more info.

Thanks @einsteinx2 Let me know if you need any other info.

**Comment by einsteinx2** [comment]
Quick update, I can confirm that I'm seeing an issue trying to add this SPM package locally on my machine using Xcode 13. I'll update this issue as soon as I find a resoltion.

**Comment by einsteinx2** [comment]
@coolioxlr So I did some more testing, created a fresh project and added the package in SPM and now I'm not seeing any errors. Can you provide any more information about the project, for example what SPM packages do you have added (did you manually add `mparticle-apple-sdk` separately vs having the kit pull it in as a dependency, and what versions do you have pinned for your SPM packages)? 

Also are you seeing any issues on your local machine using Xcode 13 or only in CI with AppCenter?

**Comment by coolioxlr** [comment]
@einsteinx2 we don't have any issue using our local machine both M1 or Intel Mac using Xcode 13. We are only seeing the problem in AppCenter. If we remove the mParticle-AppsFlyer then it builds fine. I also notice mParticle-AppsFlyer library haven't been update for more than 6 months so I forked it and use try to use latest version of appsflyer but still no luck.

Everything is working fine in AppCenter when using Xcode12 build. We have Xcode to pull the packages automatically. Currently using mParticle-Apple-SDK 8.4.0 - Next Major and mParticle-AppsFlyer 8.0.7

**Comment by einsteinx2** [comment]
@coolioxlr Unfortunately since this issue doesn't manifest locally using Xcode 13 on any of our machines, it appears to be an issue specific to AppCenter's macOS runner. This is outside of our control and should be brought up with AppCenter support as there looks to potentially be a misconfiguration or some other platform specific problem on their side. If you do end up finding a workaround that requires changes to our code or SPM configuration, we're happy to accept PRs to merge that in so you don't need to use a fork.
