### ISSUE TITLE
MPAppDelegateProxy does not forward protocol conformance

### ISSUE THREAD

**Issue by cbaltzer** [mParticle/mparticle-apple-sdk#143]
We have a React Native app that uses mParticle in combination with [react-native-app-auth](https://github.com/FormidableLabs/react-native-app-auth). Implementing this involves adding a property and a protocol to our AppDelegate. 

`MPAppDelegateProxy` is intercepting calls to the app delegate, which is normally no problem because it forwards all selectors. However, it appears that RN checks `conformsToProtocol` before calling the selector, which `MPAppDelegateProxy` does not implement. The flow works if we add the necessary protocol to `MPAppDelegateProxy` directly, but that's not a workable solution as it gets overwritten any time we do a pod install (in CI/CD builds for example).  

PR: #144

**Comment by einsteinx2** [comment]
This fix has just gone out with release v8.8.0: https://github.com/mParticle/mparticle-apple-sdk/releases/tag/v8.8.0
