### ISSUE TITLE
`Attempted to dereference garbage pointer` crashes in `std::string` copy constructor

### ISSUE THREAD

**Issue by tiwoc** [mParticle/mparticle-apple-sdk#145]
We're seeing a lot of `Attempted to dereference garbage pointer` crashes recently in the copy constructor of `std::string` when called from the mParticle SDK. About 0.5% of all user sessions end with this type of crash currently.

The most common case is this one in `-[MPPersistenceController fetchSessionEndMessageInSession:]`:

```
Hardware Model:     iPhone11,8
Role:               Foreground
OS Version:         iOS 14.8.1
Exception Type:     EXC_BAD_ACCESS 
Exception Subtype:  KERN_INVALID_ADDRESS


EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x47.

0  libc++.1.dylib          std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
1  <redacted>              -[MPPersistenceController fetchSessionEndMessageInSession:] (MPPersistenceController.mm:1241:40)
2  <redacted>              -[MPBackendController confirmEndSessionMessage:] (MPBackendController.mm:290:26)
3  <redacted>              -[MPBackendController uploadOpenSessions:completionHandler:] (MPBackendController.mm:826:9)
4  <redacted>              -[MPBackendController processOpenSessionsEndingCurrent:completionHandler:] (MPBackendController.mm:514:5)
5  <redacted>              __132-[MPBackendController startWithKey:secret:firstRun:installationType:proxyAppDelegate:startKitsAsync:consentState:completionHandler:]_block_invoke_2 (MPBackendController.mm:1868:9)
6  libdispatch.dylib       __dispatch_call_block_and_release
7  libdispatch.dylib       __dispatch_client_callout
8  libdispatch.dylib       __dispatch_lane_serial_drain
9  libdispatch.dylib       __dispatch_lane_invoke
10 libdispatch.dylib       __dispatch_workloop_worker_thread
11 libsystem_pthread.dylib _pthread_wqthread
```

There's one other case in `-[MPKitContainer filter:forEvent:selector:]` that doesn't happen quite as often:

```
Hardware Model:     iPhone11,8
Role:               Foreground
OS Version:         iOS 14.8.1
Exception Type:     EXC_BAD_ACCESS 
Exception Subtype:  KERN_INVALID_ADDRESS


EXC_BAD_ACCESS: Attempted to dereference garbage pointer 0x77.

0  libc++.1.dylib    std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)
1  <redacted>        -[MPKitContainer filter:forEvent:selector:] (MPKitContainer.mm:806:49)
2  <redacted>        -[MPKitContainer forwardSDKCall:event:parameters:messageType:userInfo:] (MPKitContainer.mm:2211:13)
3  <redacted>        __28-[MParticle logCustomEvent:]_block_invoke_3 (mParticle.m:898:17)
4  libdispatch.dylib __dispatch_call_block_and_release
5  libdispatch.dylib __dispatch_client_callout
6  libdispatch.dylib __dispatch_main_queue_callback_4CF
7  CoreFoundation    ___CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
8  CoreFoundation    ___CFRunLoopRun
9  CoreFoundation    _CFRunLoopRunSpecific
10 GraphicsServices  _GSEventRunModal
11 UIKitCore         -[UIApplication _run]
12 UIKitCore         _UIApplicationMain
13 <redacted>        static Application.main() (Application.swift:42:9)
14 <redacted>        static Application.$main() (Application.swift:14:1)
15 libdyld.dylib     _start
```

One notable property of this is that **all crashes we're seeing are happening on various minor versions of iOS 14**, which is the lowest iOS version we support. We've not seen a single crash on iOS 15 yet.

Another thing of note is that in both cases, a pattern is used where a static `NSString` is converted to a `std::string` via the `UTF8String` property of `NSString`, stored in a `std::vector`, and then retrieved via `operator[]`. This result is then copied into a new string at the call site, which is where the app crashes.

These crashes also happen on the whole range of iPhones. There's no obvious pattern here.

mParticle SDKs included in the app (via CocoaPods):
- mParticle SDK 8.7.0
- mParticle Braze/Appboy 8.0.15

Xcode version: 13.3 (13E113)

**Comment by tiwoc** [comment]
We now found that this is a persistent crash, in that restarting the app after the crash crashes it again. The only recourse for users seems to be to re-install the app. We still haven't found a way to reproduce, unfortunately.

**Comment by tiwoc** [comment]
These might not be related to the crashes, but I found two cases of undefined behavior that were already known (annotated with `__attribute__((no_sanitize("integer")))`) but that could be easily fixed, and one potential memory issue in the mParticle SDK.

### Signed integer undefined behavior
Signed integer overflows and left-shifting negative signed integers are undefined behavior in C/C++. `Hasher::hashFromString` triggers both kinds of UB in line 17:

https://github.com/mParticle/mparticle-apple-sdk/blob/c827eae8eb46f1c813a095b353b45784e6e05423/mParticle-Apple-SDK/Utils/MPHasher.cpp#L6-L21

When running our app with the Undefined Behavior Sanitizer enabled after removing the `__attribute__` line, these warnings show up:

> Undefined Behavior: Left shift of negative value -907040683
>
> Undefined Behavior: Signed integer overflow: -2136189024 - 1946510013 cannot be represented in type 'int'

A similar thing happens on line 72:

https://github.com/mParticle/mparticle-apple-sdk/blob/c827eae8eb46f1c813a095b353b45784e6e05423/mParticle-Apple-SDK/Utils/MPHasher.cpp#L65-L77

> Undefined Behavior: Signed integer overflow: -3750763034362895519 * 1099511628211 cannot be represented in type 'long long'

Both lines would be legal C++ code if they used unsigned integers, so a valid fix would be to do the operations on unsigned integers (`unsigned int hash` and `uint64_t rampHash`) and then cast to a signed integer before returning.

### Memory issue in `MPAliasResponse.errorResponse`

`MPAliasResponse.errorResponse` does not retain the value that is assigned to it, it just copies the pointer.

https://github.com/mParticle/mparticle-apple-sdk/blob/c827eae8eb46f1c813a095b353b45784e6e05423/mParticle-Apple-SDK/Include/MPAliasResponse.h#L20-L23

This will become a dangling pointer as soon as the assigned value goes out of scope. It should be replaced with `@property (nonatomic, strong) NSString *errorResponse;`

**Comment by einsteinx2** [comment]
Tracking these internally in the following tickets:

https://go.mparticle.com/work/SQDSDKS-3658
https://go.mparticle.com/work/SQDSDKS-3659
https://go.mparticle.com/work/SQDSDKS-3660

**Comment by tiwoc** [comment]
Downgrading from Xcode 13.3 to Xcode 13.2.1 fixed the crashes, so this could also be a compiler/linker bug. We'll be testing 13.3.1 for the next app release to see if the crash on iOS 14 and earlier that was [fixed in that release](https://developer.apple.com/documentation/xcode-release-notes/xcode-13_3_1-release-notes) is the same one that we're seeing.

**Comment by tiwoc** [comment]
Good news: We don't see these crashes when building the app with Xcode 13.3.1 either 🎉 This must have been an issue with 13.3 only.

I'm closing this issue because the original bug can be fixed by upgrading Xcode, but I think it would still make sense to fix the undefined behavior and dangling pointer to prevent other kinds of crashes.

**Comment by einsteinx2** [comment]
@tiwoc Thanks for the update. Although it looks like this issue may have resolved itself, we went ahead and took action to prevent this from potentially happening again in the future. We're in the process of slowly removing much of the legacy C++ code in the SDK, and have refactored this part to get rid of the use of std::string altogether, as it was unnecessary anyway.
