### ISSUE TITLE
Cocoapods warning/mParticle_Apple_SDK not found

### ISSUE THREAD

**Issue by mrspeaker** [mParticle/mparticle-apple-sdk#18]
Hey, sorry for treating this like tech support, but if I follow the instructions from the [https://app.mparticle.com/quickstart](quickstart) it gives me an error about being deprecated:

```
pod 'mParticle' , :git => 'git@github.com:mParticle/mParticlePod.git'
#import <mparticle/mParticle.h>
```

And if I follow the instructions on the [repo](https://github.com/mParticle/mparticle-apple-sdk) and add:

```
target 'ps' do
  pod 'mParticle-Apple-SDK', '~> 5', :subspecs => ['BranchMetrics']
end
```

(app target is `ps`) To my podfile, I get a warning when I do `pod install`:

```[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. 
In order for CocoaPods integration to work at all, please either set the base configurations of the target `ps` to 
`../Pods/Target Support Files/Pods-ps/Pods-ps.debug.xcconfig` or include the 
`../Pods/Target Support Files/Pods-ps/Pods-ps.debug.xcconfig` in your build configuration.```

If I ignore the warning and add `@import mParticle_Apple_SDK` to my AppDelegate.m, I get an error `Module 'mParticle_Apple_SDK' not found`.

Do you know which method is correct, and anything I could do to troubleshoot? Thanks!

**Comment by dcirne** [comment]
Let's try to get your project up and running. 

We have an updated set of instructions on the README from our GitHub repository. Please take a look at: https://github.com/mParticle/mparticle-apple-sdk

As a quick start you can add the mParticle SDK to your `Podfile`:

```ruby
target '<Your Target>' do
    pod 'mParticle-Apple-SDK', '~> 5', :subspecs => ['BranchMetrics']
end
```

And the import statement should be:
```objective-c
@import mParticle_Apple_SDK;
```

Please let us know if you have any questions. You can reach us directly at: support@mparticle.com
