### ISSUE TITLE
Is there a way to set a list of super properties to send with all track events?

### ISSUE THREAD

**Issue by malcommac** [mParticle/mparticle-apple-sdk#184]
Hi, we're implementing mParticle to track and send events.  
Our current implementation relies on MixPanel, where we can set a list of super properties via `mixpanelSDK.registerSuperProperties()` to register a set of properties added automatically to each event sent automatically. Is there a similar option on mParticle?

**Comment by samdozor** [comment]
Hi @malcommac there is currently no out of the box way to do this. If this is still a blocker for you - please reach out to our support team (support@mparticle.com) so we can record a product-feature request for it. Thank you!
