### ISSUE TITLE
mParticle Appboy/Braze integration won't build if you use the No Location target

### ISSUE THREAD

**Issue by horsejockey** [mParticle/mparticle-apple-sdk#192]
This should probably be an issue in the AppBoy/Braze integration repo but it doesn't allow issues. Hoping this can find its way to the correct team. There is a bundle identifier collision if you use the no location mParticle apple SDK because the Appboy/Braze integration ends up importing the other version of the SDK. The Appboy/Braze integration will also need a target that only uses the no location target.

**Comment by einsteinx2** [comment]
Thanks for the report, can you please confirm which package manager you're using?

**Comment by horsejockey** [comment]
Swift package manager. Thanks!

**Comment by horsejockey** [comment]
@einsteinx2 I'd love to know if this is something you will add support for or if I should try and figure out a workaround.

**Comment by einsteinx2** [comment]
@horsejockey Sorry for the delayed reply, I have this ticket in my sprint now. I think we're likely going to need to add a NoLocation SPM target in all kit repositories to resolve the issue, though before we do that I'm trying to see if there's any other way around it. 

If you need a workaround for the moment, you can fork this repo and change the dependency in Package.swift to point to the NoLocation target and that should work.

I'll update this ticket once we have a proper fix in place (whether that's adding a NoLocation target or something else)

**Comment by einsteinx2** [comment]
Now tracking internally as https://go.mparticle.com/work/SQDSDKS-5439

**Comment by einsteinx2** [comment]
This is now live with the latest release [8.2.1](https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/releases/tag/8.2.1). You'll need to remove the dependency from your project and add it again. When you do you'll now see two target options. Please check the box next to the `mParticle-Appboy-NoLocation`.

If you run into issues, there can be leftover problems with the SPM cache that can be resolved by completely closing Xcode (not just the project but the whole app), deleting derived data, then deleting the SPM cache located at `~Library/Caches/org.swift.swiftpm`.

**Comment by horsejockey** [comment]
Amazing! Thank you!
