### ISSUE TITLE
'mParticle_Apple_SDK/mParticle_Apple_SDK-Swift.h' file not found

### ISSUE THREAD

**Issue by ashuiOSDeveloper** [mParticle/mparticle-apple-sdk#195]
I am trying to build an app which has mParticle Apple SDK installed via cocoapods.
But I am getting this error in m-Particle-Apple-SDK > mParticle > Swift.h

**Comment by einsteinx2** [comment]
Hi, please make sure that you have `!use_frameworks` in your Podfile and then run `pod update` again.

We actually just recently updated the readme in this repo but it hasn’t been merged into main yet, you can see the updated example here: https://github.com/mParticle/mparticle-apple-sdk/tree/development#cocoapods

Please re-open this issue if that doesn’t resolve your problem.

**Comment by ashuiOSDeveloper** [comment]
Hi,
I have added `use_frameworks` in my podfile and ran `arch -x86_64 pod update` as I am using Apple M1.
I am still getting the same error.
