### ISSUE TITLE
MPAppBoyKit in app messages are not displaying

### ISSUE THREAD

**Issue by horsejockey** [mParticle/mparticle-apple-sdk#196]
Logging the issue here once again because the kit doesn't allow issues to be reported. 

We don't use in app messages often but we did have them working one point. I tested them today and realized they no longer appeared. Decided to update to the latest mParticle and mParticle appboy kit releases and still was unable to get the in app message ui to show. I tried using `MPKitAppboy.setInAppMessageControllerDelegate(self)` as well as getting the braze instance from the kit and setting `braze.inAppMessagePresenter = BrazeInAppMessageUI()`. Decided to test removing the mParticle app boy kit and initialize braze myself and call braze methods for pushes instead of calling mParticle and it worked fine. 

I am wondering if there is some trick Im missing to get it to work or if there is a bug in the kit code perhaps.

**Comment by einsteinx2** [comment]
Hi @horsejockey can you confirm which company you work for so I can get someone from the TSE team that's working on your account to do a triage on this? I handled the build issues directly as we just moved to supporting Swift in the mParticle SDK and it seemed like that may have been related, but for issues like this a TSE will reproduce and attempt to resolve first before it's escalated to the dev team. If you can't or don't want to post that information publicly, please email me directly at bbaron@mparticle.com thanks.

**Comment by horsejockey** [comment]
Thanks, I work for Route App LLC.

**Comment by mmustafa-tse** [comment]
Hi @horsejockey,

Do you have an existing support ticket regarding this issue? If not, can you please file one using this [link](https://support.mparticle.com/)?

Thanks,

**Comment by einsteinx2** [comment]
HI as of the latest update to the Braze Kit this should now be working!
