### ISSUE TITLE
Pod error with use_frameworks!

### ISSUE THREAD

**Issue by barisozr** [mParticle/mparticle-apple-sdk#20]
I've a demo project to integrate your SDK for using Localytics. Podfile is:

`
platform :ios, '8.0'

use_frameworks!

target 'TestLocalytics' do

pod 'mParticle-Apple-SDK', '~> 5', :subspecs => ['Localytics']

end
`

When I tried to 'pod update' the following error occurred:

**[!] The 'Pods-TestLocalytics' target has transitive dependencies that include static binaries: (/Users/barisozer/Desktop/workspace/Samples/TestLocalytics/Pods/Localytics/Localytics-iOS-3.8.0/libLocalytics.a)** 

I can use pod 'Localytics' with use_frameworks! without any error by the way.

**Comment by rshehata** [comment]
Hello,

As per email discussion with Ufuk, we've made an update to our iOS SDK today to address this issue you're seeing with Localytics. This addressed in v5.5.2  iOS release.

You will need to include the following pre_install snippet in your podfile. I've included a complete podfile for your quick reference below.

# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

pre_install do |pre_i|
    def pre_i.verify_no_static_framework_transitive_dependencies; end
end

target 'Demo iOS' do
    #pod 'mParticle-Apple-SDK', '~> 5'
    pod 'mParticle-Apple-SDK', '~> 5', :subspecs => ['Localytics']
end

In the future, please send your support related questions to:
support@mparticle.com

Thanks again!
