### ISSUE TITLE
Xcode 15.0.0 Beta 2 - Compliation Errors

### ISSUE THREAD

**Issue by jgallantgs** [mParticle/mparticle-apple-sdk#201]
Hello :) - We are trying to compile our project on the new Xcode 15 beta and are running into issues with mParticle.

<img width="320" alt="image" src="https://github.com/mParticle/mparticle-apple-sdk/assets/114911226/d931df2c-d0f1-4d2e-a14a-1204da7234b4">

**Comment by einsteinx2** [comment]
Thanks for reporting this. We are currently investigating, but can you please confirm which package manager you’re using (CocoaPods or SPM)?

**Comment by Ded77** [comment]
On my side, with Xcode beta I have this error: `MPIConstant.h file not found`
mParticle version 8.12.0, integrated with SPM

<img width="295" alt="image" src="https://github.com/mParticle/mparticle-apple-sdk/assets/1685486/4a905caa-882f-407b-8858-b9e6d7ac3023">

**Comment by BrandonStalnaker** [comment]
I confirmed there is no issue when using Cocoapods first. Then, with our SPM example project, I did have these import issues initially but once I called `Update To Latest Package Version` I was able to run the app with our SDK just fine. Let me know if this doesn't resolve it, though I'm pretty sure it's an SPM cache issue.
<img width="1144" alt="Screenshot 2023-06-23 at 9 57 37 AM" src="https://github.com/mParticle/mparticle-apple-sdk/assets/33703490/5a394cd6-266f-46a5-bfe2-ea1e7ce6b40a">

**Comment by jgallantgs** [comment]
> I confirmed there is no issue when using Cocoapods first. Then, with our SPM example project, I did have these import issues initially but once I called `Update To Latest Package Version` I was able to run the app with our SDK just fine. Let me know if this doesn't resolve it, though I'm pretty sure it's an SPM cache issue.
> <img alt="Screenshot 2023-06-23 at 9 57 37 AM" width="1144" src="https://user-images.githubusercontent.com/33703490/248289901-5a394cd6-266f-46a5-bfe2-ea1e7ce6b40a.png">

This worked for me! Thank you. To confirm I am using SPM as well.

**Comment by erickpac** [comment]
> I confirmed there is no issue when using Cocoapods first. Then, with our SPM example project, I did have these import issues initially but once I called `Update To Latest Package Version` I was able to run the app with our SDK just fine. Let me know if this doesn't resolve it, though I'm pretty sure it's an SPM cache issue. <img alt="Screenshot 2023-06-23 at 9 57 37 AM" width="1144" src="https://user-images.githubusercontent.com/33703490/248289901-5a394cd6-266f-46a5-bfe2-ea1e7ce6b40a.png">

hey sir @BrandonStalnaker, one question, which version SPM do you have? I'm on 8.8.1 and I called `Update To Latest Package Version` and it's still not working

<img width="527" alt="image" src="https://github.com/mParticle/mparticle-apple-sdk/assets/4453794/2b79ea70-9098-459c-a72a-7b43e0ecae63">
