### ISSUE TITLE
MPInstallationTypeAutodetect uses user defaults, which isn't reliable

### ISSUE THREAD

**Issue by kballard** [mParticle/mparticle-apple-sdk#21]
Reading through the SDK source, it appears that `MPInstallationTypeAutodetect` uses `NSUserDefaults` to detect whether it's an upgrade (via properties on `MPApplication`). Unfortunately, this means that any app that clears its entire user defaults will also break mParticle's auto-detection. This affects us because our app blows away the entire user defaults when the user logs out (so that way defaults set for one user can't affect another).

A more robust solution would be to create a plist in the Application Support folder (or a subfolder thereof) as it's much less likely that an application will blow away the entire contents of Application Support.

**Comment by paulmand** [comment]
Hi @kballard thanks for the feedback! We can look into this architecture change. As an app launching with mParticle fir the first time, we actually recommending disabling auto-detect anyway, as it matters for the app releases after the first one that includes mParticle. For your implementation, you can leave the manual setting we recommend for the first release in there for subsequent releases. This has been accounted for in the customized data plan we are using for your implementation so you should be all set here.

**Comment by kballard** [comment]
Thanks for the response. It occurs to me that another reason in favor of making this change, even if the app doesn't blow away NSUserDefaults, is because you're using keys that might conceivably be used by the app already. In fact, you appear to be using a whole slew of keys for various reasons, all of which could conflict with the app (e.g. `"firstrun"`, `"asv"`, `"asb"`, `"ict"`, etc). Besides the approach I already suggested, this particular issue could be solved by prefixing all of your user defaults key names with something unique, e.g. `"com.mParticle.firstrun"`, `"com.mParticle.asv"`, etc. But if you're going to go through the trouble of fixing this issue, you may as well switch to the separate plist in order to fix both issues at the same time.

**Comment by paulmand** [comment]
HI @kballard - all of our leys are already prefixed with mParticle, so we should be set there.

**Comment by kballard** [comment]
Ah hah, [so they are](https://github.com/mParticle/mparticle-apple-sdk/blob/master/mParticle-Apple-SDK/Utils/NSUserDefaults+mParticle.m#L27). I didn't read that file because I assumed `userDefaults[someKey]`'s behavior was obvious, but apparently not. That's good to hear.

**Comment by kballard** [comment]
@paulmand When you say "leave the manual setting [you] recommend for the first release in there for subsequent releases", what manual setting is it? The [Mobile SDK Guide](http://docs.mparticle.com/#initialize-the-sdk) doesn't seem to give any recommendations here. Was this some instruction that was provided directly to whomever set up the data plan? If so, it wasn't communicated to our engineering team.

**Comment by paulmand** [comment]
Hi @kballard - please work directly with Enu on the Postmates side and Rashel from mParticle on this one as they are right people to work with to make sure you're getting what you need here. Let me know if you need their contact information and I'll send it to you outside of this forum.

**Comment by kballard** [comment]
Thanks, just knowing it's Enu I need to talk to is sufficient.
