### ISSUE TITLE
MPAppDelegateProxy forwards methods to MPSurrogateAppDelegate that it shouldn't

### ISSUE THREAD

**Issue by kballard** [mParticle/mparticle-apple-sdk#24]
`MPAppDelegateProxy` forwards all methods to `MPSurrogateAppDelegate` that it responds to, and only sends messages to the original app delegate if `MPSurrogateAppDelegate` doesn't handle it. This causes several problems, including:

* Invoking `-conformsToProtocol:` returns a result based on whether `MPSurrogateAppDelegate` conforms rather than the real app delegate.
* Adding KVO observers to the app delegate adds them to `MPSurrogateAppDelegate` instead.

I'm sure there are other issues too, but basically, any method that `NSObject` responds to will be incorrectly sent to `MPSurrogateAppDelegate` instead of the original app delegate.

**Comment by dcirne** [comment]
Hi Kevin,

The `MPSurrogateAppDelegate` is a convenience class to handle a lot of the boiler plate code that is needed for instrumenting push notifications, deep-linking, app launching, etc. 

Our SDK by default proxies the App Delegate making your life easier. However, if you have overloaded the app delegate with methods and need the proxy mechanism to be turned off, you can do so by starting the mParticle SDK passing the *NO* to proxyingAppDelegate.

```objective-c
- (void)startWithKey:(nonnull NSString *)apiKey 
              secret:(nonnull NSString *)secret
    installationType:(MPInstallationType)installationType 
         environment:(MPEnvironment)environment 
    proxyAppDelegate:(BOOL)proxyAppDelegate;
```

By doing so `MPSurrogateAppDelegate` is taken out of the equation. However, in order for the mParticle SDK to handle the events above properly, you will need to forward that information to the SDK as described in our documentation at: http://docs.mparticle.com/#appdelegate-proxy-ios-and-tvos

**Comment by kballard** [comment]
I know how to turn off the proxy, but this bug report is still valid. The way you're doing proxying, you break a *lot* of perfectly legitimate and not-uncommon ways people use app delegates. You can fix this without removing `MPSurrogateAppDelegate`, it's just more work (since `MPAppDelegateProxy` has to know specifically which methods to forward on to `MPSurrogateAppDelegate`).

**Comment by kballard** [comment]
Also, I suggested removing `MPSurrogateAppDelegate` because the only code that uses it is `MPAppDelegateProxy`, and so there seems to be no benefit in using a second class instead of just moving its methods into `MPAppDelegateProxy` directly.

**Comment by dcirne** [comment]
@kballard, We have added support to `conformsToProtocol:` in the latest release of the SDK (6.0.7). The implementation has been done in this commit: https://github.com/mParticle/mparticle-apple-sdk/commit/db233e8f7565eab099826e59153d58efac19cfc8
