### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by sashabaranov** [mParticle/mparticle-apple-sdk#243]
From [Apple docs](https://developer.apple.com/support/third-party-SDK-requirements/):

> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies.

Could you please add a privacy manifest for this library?

It would also make sense to add privacy manifests to adapters e.g.
https://github.com/mparticle-integrations/mparticle-apple-integration-appboy
https://github.com/mparticle-integrations/mparticle-apple-integration-branchmetrics

**Comment by einsteinx2** [comment]
Hi, release 8.19.0 includes a privacy manifest (https://github.com/mParticle/mparticle-apple-sdk/releases/tag/v8.19.0) and we are actively rolling out manifests to each kit and updating partner SDKs as they release manifests. Please note that our kits themselves don't do any tracking or use restricted APIs so the manifests are mostly empty, the majority of manifest information will come from the partner SDKs.

As of the time I'm writing this, both kits you links include privacy manifests and we're actively rolling out the rest starting with the most popular kits and working down from there.
