### ISSUE TITLE
PrivacyInfo.xcprivacy is not included when installing with CocoaPods

### ISSUE THREAD

**Issue by jmartycak-rbi** [mParticle/mparticle-apple-sdk#269]
Hey, I noticed when installing `mPaticle-Apple-SDK` with CocoaPods the `PrivacyInfo.xcprivacy` file is not included. I checked the podspec in your repository and noticed you're not using the `resource_bundles` property to expose it.

It's pretty simple change in the podspec file. You can refer to [this thread in Apple Developer forums](https://forums.developer.apple.com/forums/thread/745546?answerId=778503022#778503022) to see how it's done.

Could you please try to fix this?

**Comment by BrandonStalnaker** [comment]
Thanks for the heads up on this! We've added the privacy manifest to the resource bundle so it should be appearing for cocoapods projects now. Sorry for the delay and if you have the chance to confirm this is working for you we'd love to hear back.
