### ISSUE TITLE
iAd framework usage

### ISSUE THREAD

**Issue by IvanGLV** [mParticle/mparticle-apple-sdk#278]
Hello!

Recently we've figured out that `mParticle` brings `iAd framewrok` as a dependency (please see attached screenshot) but according to [Apple docs](https://developer.apple.com/documentation/iad) this framework is deprecated and gonna be completely removed from iOS so that all apps that are using it won't work anymore. 
The version of mParticle we're using is **8.24.1**

Could you please give us an ETA when `iAd` will be removed from `mParticle`?

![image](https://github.com/mParticle/mparticle-apple-sdk/assets/112630172/1bd686c2-875d-45cb-8371-ed07dafa8648)

**Comment by einsteinx2** [comment]
In the code just below the cutoff of your screenshot, you'll see that we currently check for the iOS version and `AdServices` availability and will use that on all the devices that are on at least iOS 14.3. 

We have a ticket in our backlog to remove the iAd framework support as it's been long enough now that the dual compatibility is no longer necessary or even functional. 

It looks like this is fairly trivial to remove so I'll try and get this done for the next SDK release.

**Comment by IvanGLV** [comment]
@einsteinx2 Thank you very much 🙌
