### ISSUE TITLE
Disabling silent notification registration

### ISSUE THREAD

**Issue by mclaughj** [mParticle/mparticle-apple-sdk#28]
In [`MPNotificationController.mm`](https://github.com/mParticle/mparticle-apple-sdk/blob/master/mParticle-Apple-SDK/Notifications/MPNotificationController.mm#L565-L577), there's a call to register for remote notifications silently. Is there a way to disable this call or postpone it from happening at launch? Will this cause any adverse side effects?

**Comment by dcirne** [comment]
Hi @mclaughj,

Registering for silent notifications does not prompt permission from the user, it is intended for provide update functionality to an app or library. There are no side effects.

**Comment by mclaughj** [comment]
@dcirne We have been relying on a call to the system to check if we've already registered for remote notifications (`[[UIApplication sharedApplication] isRegisteredForRemoteNotifications]`) before displaying a prompt to the user on first launch. The call in `MPNotificationController.mm` precedes our call, so we're wondering if there's a way to delay it from happening or disable it entirely.

**Comment by dcirne** [comment]
@mclaughj when do you need to check whether you're registered for notifications? We can probably delay the registration to the next run loop, but probably not much further. The registration for notification is an important data point we collect and is fundamental for some kits to work properly.

Let me know what you have in mind and together we can find a solution for this.

**Comment by mclaughj** [comment]
@dcirne We'd need to delay the registration longer than that, we're waiting for several user actions. We'll look to implement our logic another way. 

In the meantime, what would the side effects be if we disabled that call on our own fork of the SDK? (For right now, we're only relying on the Branch integration, if that matters.)

**Comment by dcirne** [comment]
@mclaughj, we can take a look into a way to disable the automatic registration for silent notifications. Perhaps an option would be in the SDK configuration file `MParticleConfig.plist` (http://docs.mparticle.com/#apple). Using this file is optional, but if you choose to use it, you can initialize the SDK with API Key, Secret, and other parameters. If we add a new parameter over there, we wouldn't need to change any public API method signature.

In terms of side effects using a fork, even though we don't recommend it for the long run, since you're only integrating with Branch, you should see no impact, as long as at some point you register to receive remote notifications, so we can collect the device token.

**Comment by twobitlabs** [comment]
That'd be great if we had a way to disable it in the SDK! 

We have a super complicated push notification opt-in and preference syncing flow that's dependent on a bunch of user state to optimize the user opting-in. It's causing a number of issues with our code to have `[[UIApplication sharedApplication] isRegisteredForRemoteNotifications]` returning true and to get the delegate callback with a device token before we've called registerForRemoteNotifications ourselves.

The `ParticleConfig.plist` would work great, or just a a call like `[[MParticle sharedInstance] disableAutomaticRegisterForRemoteNotifications]` before we call `startWithKey` would work too.

**Comment by dcirne** [comment]
Hi @mclaughj @twobitlabs, we have released SDK version 6.4.0 which implements a configuration option in `MParticleConfig.plist` to opt in/out of automatic silent notification registration. When you add the boolean key `register_for_silent_notifications` and set it to `NO`, the mParticle SDK will not try to register for silent notifications. You can see more at the docs site: http://docs.mparticle.com/#apple

**Comment by mclaughj** [comment]
Excellent, thank you!
