### ISSUE TITLE
using [NSBundle mainBundle] will always be nil when used in project with use_frameworks!

### ISSUE THREAD

**Issue by klivin** [mParticle/mparticle-apple-sdk#29]
Compiling 3rd party libs with use_frameworks! is becoming more popular due to many advantages of dynamic frameworks security/compile speed/namespacing...

Your library makes many references to NSBundle mainBundle, which will always return nil in this case and will have unintended problems using your library.

Cocoapods suggests:
Pod authors were able to use mainBundle referencing to include resources the Pod brought into the app bundle. But with frameworks, you have to make sure that you reference them more specifically by getting a reference to your framework's bundle e.g.

see http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/

**Comment by dcirne** [comment]
Hi @klivin, thanks for the feedback.

When using `NSBundle` in the mParticle SDK we are referencing the host app's bundle, not the SDK's bundle. In that case the bundle will likely return a valid instance.

Do you have a particular case where you are seeing the case you described happening? If yes, could you provide some sample code?

**Comment by klivin** [comment]
I believe this was a project configuration error that is now fixed, thank you!
