### ISSUE TITLE
Release 6.8.0 .framework binary not built with iOS 10 Base SDK

### ISSUE THREAD

**Issue by saniul** [mParticle/mparticle-apple-sdk#31]
Using Carthage with default options just the binary .framework, instead of building mParticle from source. The [published .framework](https://github.com/mParticle/mparticle-apple-sdk/releases/tag/6.8.0) links just fine with the application, but trying to call `-[MParticle userNotificationCenter:willPresentNotification:]` or `-[MParticle userNotificationCenter:didReceiveNotificationResponse:]` crashes at runtime with an unrecognized selector.

Looks like the [Release 6.8.0 .framework binary](https://github.com/mParticle/mparticle-apple-sdk/releases/tag/6.8.0) was not built with iOS 10 Base SDK (i.e. it was not built with Xcode 8). As a result, anything that was wrapped in a `__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_10_0` conditional macro in mParticle's implementation files is not actually in the built product.

**Comment by saniul** [comment]
Confirmed with class-dump too:
![screen shot 2016-09-17 at 02 04 26](https://cloud.githubusercontent.com/assets/371773/18604863/18cdcede-7c7b-11e6-8a4b-0d9104f38ce9.png)

^ Here I'm running class-dump on the .framework from the archive downloaded from the [3.8.0 release page](https://github.com/mParticle/mparticle-apple-sdk/releases/tag/6.8.0). As you can see, if I `grep` the output to find an occurrence of `userNotificationCenter:` - nothing is found. In contrast, if I grep by `userSegments:` I get a result. 

The `userSegments:endpointId:completionHandler:` method is defined in `mParticle.m` right after `-[MParticle userNotificationCenter:willPresentNotification:]` and `-[MParticle userNotificationCenter:didReceiveNotificationResponse:]`.

**Comment by akatz0813** [comment]
@saniul we will have this resolved ASAP.

**Comment by dcirne** [comment]
Hi @saniul, thanks for the feedback and for catching the issue. A new framework has been uploaded. Please let us know if all is working for you.

**Comment by saniul** [comment]
Verified, thank you for the fix!
