### ISSUE TITLE
mParticle keeps app running in background for 3 minutes

### ISSUE THREAD

**Issue by twobitlabs** [mParticle/mparticle-apple-sdk#34]
We have observed that mParticle is calling `beginBackgroundTaskWithExpirationHandler:` when the app is backgrounded, and then failing to call `endBackgroundTask:` until iOS calls the expiration handler after 3 minutes. This keeps the app running in the background eating up battery life, making network requests, consuming CPU, etc...

The code causing the problem is in MPBackendController.mm. `beginBackgroundTask` is called when the app enters the background. Whenever that happens our app stays alive for 3 minutes before finally being suspended. If we comment out the call to `beginBackgroundTask` then the app suspends in a timely fashion.

We need our app to suspend as soon as any necessary background tasks have completed instead of always running for the full 180 seconds that iOS allows.

**Comment by dcirne** [comment]
Thank you for filing the issue @twobitlabs. We need to use a background task to correctly measure the session timeout, and ensure that data is uploaded to our servers before the app is suspended by the O.S.

We are updating the code to end the background task immediately after a session has ended and its respective batch has successfully been uploaded to our servers. In such case if you set `sessionTimeout` to a small value (minimum of 10 seconds), the background task will end in a very short amount of time.

```objective-c
[MParticle sharedInstance].sessionTimeout = 10;
```

> Note that currently the behavior of the SDK is not to keep processing things in the background, it just waits for the current session to expire and tries to upload data to our servers. The energy impact when profiling the SDK with Instruments is very low.

**Comment by twobitlabs** [comment]
The energy impact can be significant because mParticle keeps any app that utilizes its SDK awake for 3 minutes in the background. A lot of apps (like the sports app we're working on) actively poll api's (in our case for live sports data) which keeps the users cellular connection active. If I use our app 10 times in a day mParticle has unnecessarily kept the app awake for an additional 30 minutes causing a extra api calls to go out and a lot of unnecessary load on our servers.

It's fine to start a background task and upload the data but as soon as the upload is done it should call endBackgroundTask to let the app background. Session timeouts should be handled with a different mechanism than background tasks.

We are anxiously awaiting a fix for this as we've been getting user complaints about battery life and after literally spending days debugging this we finally tracked it down to mParticle keeping the app unnecessarily awake in the background.

Thanks!

**Comment by samdozor** [comment]
@twobitlabs  the update we're implementing will fix the SDK to immediately suspend based on the timeout you specify, with a default of 60 seconds. If you need to poll your servers even while in the background, we suggest setting this timeout to the minimum.

**Comment by twobitlabs** [comment]
We use a dozen analytics sdks and mParticle is the only one where our choice of the session timeout value would be coupled to how long the app stays awake in the background. 

Can't you use timestamps and user defaults to track the session timeout without keeping the app unnecessarily awake in the background? I feel like you're mis-using background tasks if you're using them to keep the app awake to track session timeouts. All of the other analytics SDK's we use use a background task to upload the data but then promptly call endBackgroundTask.

**Comment by BrianDoig** [comment]
From https://developer.apple.com/library/content/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html


> You do not need to wait until your app moves to the background to designate background tasks. A more useful design is to call the beginBackgroundTaskWithName:expirationHandler: or beginBackgroundTaskWithExpirationHandler: method before starting a task and call the endBackgroundTask: method as soon as you finish. You can even follow this pattern while your app is executing in the foreground.

It might be possible to start a background task for each session you are measuring.  That way when the session ends or times out, the app will end as soon as all of the things being tracked are finished.

**Comment by samdozor** [comment]
Thanks @BrianDoig - we're certainly going to address the issue related to not calling endBackgroundTask. We're additionally pursuing a solution whereby we don't rely on a background task at all, except for data upload, as @twobitlabs suggested.

**Comment by dcirne** [comment]
@twobitlabs, our latest SDK release, version 6.10.4, addresses ending the background task as soon as the current session has timed out and its respective data has been uploaded to mParticle. The best way to minimize the time the SDK stays running in the background is to set a short session timeout. The minimum value has been reduced to 1 second.

```objective-c
[MParticle sharedInstance].sessionTimeout = 1;
```

Please feel free to contact Paul directly if you have any questions.

**Comment by twobitlabs** [comment]
Are you working on a solution that decouples the session timeout from the amount of time the app is kept awake in the background?

**Comment by samdozor** [comment]
@twobitlabs it's something we're considering but client side session management, and making the distinction between a brief interruption and a true application-exit, is crucial for data accuracy and recency - it's a complex topic so please reach out to our support team and we'd be happy to discuss it!

**Comment by postmechanical** [comment]
This issue seems to have cropped up again in 8.2.0

```
2022-01-11 12:48:07.132482-0700 Hunt[3038:1622460] [BackgroundTask] Background Task 302 ("Called by TheApp, from -[MPBackendController beginBackgroundTask]"), was created over 30 seconds ago. In applications running in the background, this creates a risk of termination. Remember to call UIApplication.endBackgroundTask(_:) for your task in a timely manner to avoid this.
```

**Comment by thuss** [comment]
@postmechanical 8.5.4 is the current version. Are you saying it was reintroduced in 8.2.0 and that it's also present in 8.5.4?

**Comment by postmechanical** [comment]
@thuss Haven't updated to 8.5.4 yet. Will give it a go. Looking at the background task handling code I'm curious to understand why the default `sessionTimeout` is `60` rather than `30` as a value of `60` seems guaranteed to produce the incorrect behavior>

**Comment by thuss** [comment]
@postmechanical agreed, it's a bad default and definitely bit us. We've been running `sessionTimeout = 20` for a number of years now.
