### ISSUE TITLE
subscript operator for NSUserDefaults.

### ISSUE THREAD

**Issue by navisingh** [mParticle/mparticle-apple-sdk#36]
You guys wrote an extension to NSUserDefaults where you created a subscript operator for NSUserDefaults as so:  
nsuserdefaults+mparticlesdk.h/m

- (nullable id)objectForKeyedSubscript:(nonnull NSString *const)key;
- (void)setObject:(nullable id)obj forKeyedSubscript:(nonnull NSString *)key;

Problem is that we use a pod 'SwiftyUserDefaults'  which does the same in our swift-3 branch.  That creates problems because the pod does the same.  We would appreciate your removing these subscript methods from the sdk so that we can continue using particle in our swift-3 branch of the code.

**Comment by dcirne** [comment]
This has been addressed and will be released on the next 7.x-beta. Will keep the ticket open for now and close one the beta has been released.

**Comment by dcirne** [comment]
Released on SDK 7.0.0-beta3
