### ISSUE TITLE
duplicate symbol _SignalHandler

### ISSUE THREAD

**Issue by mylegfeelsfunny** [mParticle/mparticle-apple-sdk#44]
Integration Method: CocoaPods
Xcode Version: 8.3
Library Version: 6.11.2 and above
Platform: iOS
Language: Swift / Objective-C
Description:
There is a c function, SignalHandler, that is conflicting with a c function of the same name in the Mixpanel SDK.
We use both and it makes using the Cocoapod unavailable. Please name space your functions so they do not conflict.
SignalHandler
Expected Behavior:
The pod compiles in the xcode project.

**Comment by samdozor** [comment]
@hatebyte thank you for the report. Looks like this was introduced by Mixpanel in version 3.1.2 of their SDK: https://github.com/mixpanel/mixpanel-iphone/commit/e118d301540c311ca20f488f408e0cdf791a4d49

We can see what we can do to namespace this function in a future release.

For the time being - I'm able to work around the conflict by either:

1. Specify `use_frameworks!`
```
target 'MixpanelExample' do
   use_frameworks!

   pod 'mParticle-Apple-SDK', '6.14.1'
   pod 'Mixpanel', '3.1.7'
end
```

2. Or, Downgrading Mixpanel to 3.1.1 (or below)
```
target 'MixpanelExample' do
   # without use_frameworks
   # use_frameworks!

   pod 'mParticle-Apple-SDK', '6.14.1'
   pod 'Mixpanel', '3.1.1'
end
```

3. This is related to crash reporting. If you're not using our crash reporting, you can safely rename our method to MPSignalHandler, if you feel comfortable editing the Pod source.

**Comment by hatebyte** [comment]
@samdozor thank you. 

Mixpanel just named spaced their to `MPSignalHandler`. So it should not conflict anymore. 
Please don't use MP yourselves. 

How silly is that? Same namespace even.
