### ISSUE TITLE
Mixpanel Linker command failed with exit code 1(use -v to see invocation)

### ISSUE THREAD

**Issue by leozhao0709** [mParticle/mparticle-apple-sdk#45]
Hi,

Not sure what happened tonight. It's even worked this afternoon, but since tonight, when I compiled, I always get this error. If I remove mparticle pod, then my project can build correctly. 
Any ideas?

**Comment by leozhao0709** [comment]
I find if I contain the Mixpanel in my pod, then it will have this issue. So how do I fix it with mixpanel?

**Comment by leozhao0709** [comment]
seems it will work for mixpanel 2.9.9, but mixpanel 3.1.7 will trigger this error.

**Comment by samdozor** [comment]
hey @leozhao0709 - I believe this is a duplicate of https://github.com/mParticle/mparticle-apple-sdk/issues/44, closing for now.
