### ISSUE TITLE
MPUserAttributeChange violates initializer nullability

### ISSUE THREAD

**Issue by kballard** [mParticle/mparticle-apple-sdk#47]
`MPUserAttributeChange` declares its initializer as `nonnull` but it can very clearly return `nil`. I'm surprised you're not getting a compiler/static analyzer warning about this.

https://github.com/mParticle/mparticle-apple-sdk/blob/3800a9cb6958b09cd95f6b38a8dc1d620b9cc11b/mParticle-Apple-SDK/Utils/MPUserAttributeChange.m#L26-L36

**Comment by samdozor** [comment]
@kballard this should be fixed in the latest: https://github.com/mParticle/mparticle-apple-sdk/commit/c23987ef8d2de3f89041aeab1679c001426725d4
