### ISSUE TITLE
Removing user attributes fails if the attribute isn't set

### ISSUE THREAD

**Issue by kballard** [mParticle/mparticle-apple-sdk#48]
If I try to remove a user attribute, and the attribute isn't set, mParticle logs an error to my console claiming "Invalid Data Type". It looks like the culprit is the following line:

https://github.com/mParticle/mparticle-apple-sdk/blob/3800a9cb6958b09cd95f6b38a8dc1d620b9cc11b/mParticle-Apple-SDK/MPBackendController.mm#L764

Note how it's only considering the attribute as deleted if it already exists. But it shouldn't care about that; deleting an attribute that doesn't exist should be perfectly valid.

**Comment by samdozor** [comment]
@kballard this should be fixed in the latest: https://github.com/mParticle/mparticle-apple-sdk/commit/3ea89b8cedd47284d4c1b02e5e543fd6a6d05cf7
