### ISSUE TITLE
Carthage cloning issues

### ISSUE THREAD

**Issue by rhaining** [mParticle/mparticle-apple-sdk#49]
I'm seeing this frequently since I started pointing my Cartfile to mparticle v6.15.0:
```
A shell task (/usr/bin/env git submodule --quiet update --init --recursive) failed with exit code 1:
ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.
 
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:mparticle-integrations/mparticle-apple-integration-urbanairship.git' into submodule path '…Carthage/Checkouts/mparticle-apple-sdk/Kits/urbanairship-kit' failed
Failed to clone 'Kits/urbanairship-kit'. Retry scheduled
ssh_exchange_identification: read: Connection reset by peer
fatal: Could not read from remote repository.
```

it happens on a lot of htese 'kits'.  then if i retry, they're okay.

is this happening to anyone else? is there a way around this? thanks!

**Comment by samdozor** [comment]
@rhaining we recently added the Kits as submodules so perhaps that's the issue - that said we've been unable to reproduce this on our side, even after blowing away the SSH keys in our environment. Do you have any more details as to when you're seeing this? Is it specific to any particular kit, or only urban? And, does this happen with `carthage update`, or some other command? Thanks!

**Comment by rhaining** [comment]
@samdozor it seems to happen sometimes, but not all the time. I'm seeing it after running `carthage bootstrap --no-build --use-ssh --use-submodules`.

it seems to happen with any of the kits, which we're not using, but are cloned anyways.

**Comment by eseay** [comment]
@samdozor I am experiencing the same issue. The Carthage checkout hangs at:
`*** Checking out mparticle-apple-sdk at "6.15.0"` and then after some time, the next line reads out:
`A shell task (/usr/bin/env git clone --quiet git@github.com:mparticle-integrations/mparticle-apple-integration-adjust.git%` with the process quitting.

**Comment by samdozor** [comment]
hey @eseay and @rhaining we think this is related to using ssh vs. https for our submodule entries. For now we're going to remove the submodules from the repo which should resolve the issue. I'll ping here again once we've done so, thanks!

**Comment by samdozor** [comment]
@eseay and @rhaining we've pushed 6.15.3, removing submodules - please let me know if you're still seeing issues.

**Comment by rhaining** [comment]
thanks!
