### ISSUE TITLE
AppsFlyer is not getting currency for commerce events

### ISSUE THREAD

**Issue by alexandra-mikh** [mParticle/mparticle-apple-sdk#56]
Hello,
Original issue we are facing is that currency property which is passed to mParticle is not sent to AppsFlyer for commerce events.
Checking out the mparticle-apple-sdk it turns out that at some point the property is lost while copying MPCommerceEvent inside mparticle sdk. 
`__block MPCommerceEvent *forwardCommerceEvent = [commerceEvent copy];`
Checking out the MPCommerceEvent NSCopying protocol implementation, you can see that currency property is not being copied, which later is affecting AppsFlyer event setup
`if (commerceEvent.currency) {
            values[AFEventParamCurrency] = commerceEvent.currency;
  }`
I'm not sure if it was done for a reason though. 
![screen shot 2017-11-20 at 15 01 55](https://user-images.githubusercontent.com/5527326/33027960-70a7e6ce-ce0c-11e7-84a3-0100ade11a85.png)

**Comment by samdozor** [comment]
Hi @alexandra-mikh this fix has been released in SDK version 6.15.18. Thanks for your patience!

**Comment by alexandra-mikh** [comment]
Hi Sam, 

Thanks for cooperation and letting us know.

Kind regards, 
Alexandra.
