### ISSUE TITLE
Kits not activating in iOS 11

### ISSUE THREAD

**Issue by mylegfeelsfunny** [mParticle/mparticle-apple-sdk#58]
`mParticle.start(withKey: XXXXXX, secret: XXXXXX, installationType: .autodetect, environment: environment, proxyAppDelegate: false)` is activating the `AppsFlyer` and `BranchMetrics` kits fine in iOS 10.
We are observing the `mParticleKitDidBecomeActive` and `mParticleKitDidBecomeInactive` as usual. But when compiling with iOS 11, the notification are not posted. In fact, the start methods of those kits are not called either.

Am I missing something obvious in the docs?

```
    pod 'mParticle-Apple-SDK', '~> 6' (6.15.16)
    pod 'mParticle-AppsFlyer', '~> 6' (6.15.15)
    pod 'mParticle-BranchMetrics', '~> 6' (6.15.15)
```

We are also using `use_frameworks!` in our podfile but have the recommended 
```
pre_install do |pre_i|
    def pre_i.verify_no_static_framework_transitive_dependencies; end
end
```

Code base is 99% swift
minimum Target is iOS 9

We are losing all of our AppsFlyer campaign data, so it is pretty urgent for us. 
Thank you in advance.

**Comment by mylegfeelsfunny** [comment]
For a little insight, it looks like the config url is losing the in iOS 11. 
`https://config2.mparticle.com/v4/(null)/config?av=2.0.0&sv=6.15.16` is what gets set.

**Comment by mylegfeelsfunny** [comment]
We were able to narrow down the search to `MParticle.sharedInstance()` fetching the configuration before `start(withKey ...` is called on iOS 11. 
Because it is called too soon the url is malformed. Perhaps this should not happen.

**Comment by samdozor** [comment]
Hi @mylegfeelsfunny - all of our customers have apps running on iOS 11, most with kits. There is likely something that's specific to your implementation causing this. Please work with our support team and we'll get this resolved through that channel. Thanks!

**Comment by palmaya** [comment]
We are also experiencing an issue with the Adobe Kit not working in our app running iOS 11.2 
We are unable to send outbound messages to Adobe Marketing Cloud. The outbound connection is working in iOS 10.

SDK versions:
mparticle-apple-integration-adobe.framework binary at "Version 6.15.17"
mparticle-apple-sdk.framework binary at "Version 6.15.17"

**Comment by samdozor** [comment]
Hi all - this should have been address in release 6.16.1 yesterday, and will be address in 7.1.1 today. Please let us know if you're still seeing this!
