### ISSUE TITLE
Analyze Issues

### ISSUE THREAD

**Issue by soolwan** [mParticle/mparticle-apple-sdk#63]
Hello, we like to maintain a clean Build->Analyze result. I'll attach a screenshot with all the issues we see running Analyze with the mParticle SDK installed.

<img width="371" alt="screen shot 2018-02-27 at 10 11 54 am" src="https://user-images.githubusercontent.com/217295/36743189-defd9c58-1ba6-11e8-96d8-7e5ba08a4566.png">

**Comment by samdozor** [comment]
Hey @soolwan we'll be sure to clean these up for the next SDK release, either this week or next. Thanks for the report!

**Comment by samdozor** [comment]
hey @soolwan this was [fixed in 7.1.5](a41cf612e184569dfb34ae1bfc4711fabf0d678d) - sorry for the delay. We've also since released 7.2.0 which is recommended over 7.1.5 for all customers. Thanks!
