### ISSUE TITLE
App Extension creates crash on main app

### ISSUE THREAD

**Issue by maurovc** [mParticle/mparticle-apple-sdk#69]
Hey!

Today we tried to add the mParticle SDK to an iMessage app extension, since adding it we are getting a crash when trying to send the device token for push notifications to mParticle.

The crash:

`[MParticle didRegisterForRemoteNotificationsWithDeviceToken:]: unrecognized selector sent to instance`

We've seen this is related to the configuration of the flag `MPARTICLE_APP_EXTENSIONS`. We already tried the SDK in this iMessage extension and it worked. Maybe it could be a newer version of cocoapods that created this crash. After some investigation we've found out that the app ends up with only one framework in it, which it looks like is the second one compiled (the extension one -> as this overrides the previous one).

I've created a sample project that reproduces the crash, you just need to put a key and a secret to try it.

Best regards,

Mauro

[mParticleExtensionTest.zip](https://github.com/mParticle/mparticle-apple-sdk/files/2014680/mParticleExtensionTest.zip)

**Comment by samdozor** [comment]
hey @maurovc ! Sorry for the delay here. This does indeed seem to be due to something with the latest Cocoapods. We're continuing to investigate. Thanks for the report.

**Comment by maurovc** [comment]
Hey! @samdozor Any news on this?

Thanks,

Mauro

**Comment by maurovc** [comment]
It looks like fixed on the latest version + pods up to date.
