### ISSUE TITLE
Adjust delegate not configurable with mParticle-Adjust integration

### ISSUE THREAD

**Issue by maurovc** [mParticle/mparticle-apple-sdk#70]
Hey!

As there's no way to raise an issue in the https://github.com/mparticle-integrations/mparticle-apple-integration-adjust repo I decided to do it here.

We are trying to migrate to the mParticle-Adjust integration from using directly the Adjust SDK but we need to use the adjustDelegate that informs about attribution. There's no way to add this delegate to the configuration that gets passed to Adjust from mParticle.

Best,

Mauro

**Comment by samdozor** [comment]
hey @maurovc this and the other issue are currently in progress in the branch here: https://github.com/mparticle-integrations/mparticle-apple-integration-adjust/compare/update-attribution

This will let you either set your own delegate or use our attribution API to receive the same data.

Thanks for the report.

**Comment by maurovc** [comment]
Solved in mParticle v7.3.10
