### ISSUE TITLE
Update Adjust to v4.13.0

### ISSUE THREAD

**Issue by maurovc** [mParticle/mparticle-apple-sdk#71]
Hey,

This issue is related to issue #70 but we wanted to create this as a separate. We exposed using Objective-C the adjustDelegate from Adjust to configure it after mParticle notifies that the configuration has finished. We've seen that the current version that the mParticle-Adjust-Integration uses (v.4.11.0) doesn't work as expected as the delegate doesn't get called until the app goes to background for first time, this way we use the attribution information that we need since the beginning.  I've checked the direct integration with Adjust and this looks like it's an issue from their side, so please update the required version in the podspec to v4.13.0.

Thanks,

Mauro

**Comment by samdozor** [comment]
hey @maurovc this and the other issue are currently in progress in the branch here: https://github.com/mparticle-integrations/mparticle-apple-integration-adjust/compare/update-attribution

Thanks for the report.

**Comment by maurovc** [comment]
Solved in mParticle v7.3.10
