### ISSUE TITLE
crash with openUrl for iOS 8.1

### ISSUE THREAD

**Issue by snehanshuashar** [mParticle/mparticle-apple-sdk#72]
We have integrated

    pod 'mParticle-Adjust', '~>7'
    pod 'mParticle-Apple-SDK', '~> 7'

in our app, and now we see that the app crashes when we launch the app with a url for iOS 8.1 (simulator).
The same code works on higher versions of iOS, and also works if we do not initialize mparticle sdks.
What could cause this crash, and how can I fix it?

Crash log:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** setObjectForKey: key cannot be nil'
*** First throw call stack:
(
    0   CoreFoundation                      0x000000010e7e4f35 __exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010f46abb7 objc_exception_throw + 45
    2   CoreFoundation                      0x000000010e6eb998 -[__NSDictionaryM setObject:forKey:] + 968
    3   mParticle_Apple_SDK                 0x000000010cecc90c -[MPLaunchInfo initWithURL:sourceApplication:annotation:] + 604
    4   mParticle_Apple_SDK                 0x000000010cde6f46 -[MPAppNotificationHandler openURL:sourceApplication:annotation:] + 326
    5   mParticle_Apple_SDK                 0x000000010cf3070b -[MPSurrogateAppDelegate application:openURL:sourceApplication:annotation:] + 187
    6   UIKit                               0x000000010b973685 -[UIApplication _applicationOpenURL:payload:] + 185
    7   UIKit                               0x000000010b97b816 -[UIApplication _handleNonLaunchSpecificActions:forScene:withTransitionContext:] + 2380
    8   UIKit                               0x000000010b97fca9 -[UIApplication _handleApplicationActivationWithScene:transitionContext:completion:] + 1894
    9   UIKit                               0x000000010b97f2ae __88-[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:]_block_invoke + 138
    10  UIKit                               0x000000010b97f215 -[UIApplication _handleApplicationLifecycleEventWithScene:transitionContext:completion:] + 349
    11  UIKit                               0x000000010b96a31a -[UIApplication scene:didUpdateWithDiff:transitionContext:completion:] + 486
    12  FrontBoardServices                  0x00000001121442a3 __31-[FBSSerialQueue performAsync:]_block_invoke + 16
    13  CoreFoundation                      0x000000010e71a53c __CFRUNLOOP_IS_CALLING_OUT_TO_A_BLOCK__ + 12
    14  CoreFoundation                      0x000000010e710285 __CFRunLoopDoBlocks + 341
    15  CoreFoundation                      0x000000010e70fa67 __CFRunLoopRun + 887
    16  CoreFoundation                      0x000000010e70f486 CFRunLoopRunSpecific + 470
    17  GraphicsServices                    0x00000001128969f0 GSEventRunModal + 161
    18  UIKit                               0x000000010b96c420 UIApplicationMain + 1282
    19  PPH Debug                           0x0000000107220fb7 main + 151
    20  libdyld.dylib                       0x0000000110d04145 start + 1
)

**Comment by samdozor** [comment]
hey @snehanshuashar thanks for the report. We've identified the issue and will include a fix in the next SDK release, this week.

**Comment by samdozor** [comment]
hey @snehanshuashar this should be fixed in SDK 7.3.9, released last week. Thanks again for the report.

**Comment by snehanshuashar** [comment]
👍 We will test this now, thank you.
