### ISSUE TITLE
mParticle extensions don't get configured on first app start

### ISSUE THREAD

**Issue by maurovc** [mParticle/mparticle-apple-sdk#73]
Hi,

In our app we have 2 extension configured with mParticle (Adjust and Appboy). During the first time a user opens the app after installing it there's no configuration cached in the device, so the configuration is retrieved from the mParticle servers but the extensions never get configured. After this, the next time I open the app the cached configuration is used to configure both extensions. 

We are expecting the extensions to be configured after the server call if they haven't been configured before.

Can I be missing something?

Thanks,

Mauro

**Comment by samdozor** [comment]
hey @maurovc we are releasing a fix for this right now as SDK 7.3.11. Currently these is an issue if you do not set an Identity Callback listener.
