### ISSUE TITLE
Repeated crash crash on launch in MPKitAppboy.m

### ISSUE THREAD

**Issue by saniul** [mParticle/mparticle-apple-sdk#78]
After releasing a build with v7.5.7 of the SDK and the kits some of Postmates' users started encountering a repeated crash on launch: [Crash report](http://crashes.to/s/36f5095d584). 

I took a brief look at the [affected class](https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/blob/fd88157d04e8fad7ee6ccc44213572b9225a149e/mParticle-Appboy/MPKitAppboy.m#L284) but I don't see anything suspicious at first glance.

**Comment by samdozor** [comment]
thanks for the report @saniul ! Looks to be possible corrupted kit configuration for these two users. Regardless the kit shouldn't be crashing - we should be able to deploy a fix today.

**Comment by samdozor** [comment]
@saniul we've release mParticle-Appboy version 7.6.1. Core and other kits have been kept at 7.6.0.

You can review the commit here: https://github.com/mparticle-integrations/mparticle-apple-integration-appboy/commit/fa33e2bea120cadb63ea54fb95f801ba19aba794
