### ISSUE TITLE
MPAppDelegateProxy not fowarding push notification register callbacks to AppDelegate

### ISSUE THREAD

**Issue by spencerprescott** [mParticle/mparticle-apple-sdk#82]
Using earlier versions of the mParticle SDK before the introduction of the `MPSurrogateAppDelegate` and proxy, `func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data)` and `func application(_ application: UIApplication, didFailToRegisterForRemoteNotificationsWithError error: Swift.Error)` would be called after registering for remote notifications. However, after using the newest version of the SDK, those push notification callbacks are not being called on our `AppDelegate`. It looks like the `MPSurrogateAppDelegate` doesn't ever receive those messages and therefore they are not being fowarded to our `AppDelegate`.

**Comment by samdozor** [comment]
hey @spencerprescott ! `MPSurrogateAppDelegate` has been in the SDK for a very long time - what version of the SDK are you using before its introduction?

I am unable to reproduce this issue in a simple app with only mParticle's SDK in it. We've noticed an issue like when the Leanplum SDK is used, or other SDKs that Swizzle. I believe our tech service engineering team is already working with you a finding a resolution for this but I'll keep this issue open until we find the resolution.

**Comment by spencerprescott** [comment]
Hi @samdozor. Ya we're in contact with support. We were previously using version 7.2 before updating to 7.7.3. Looking at our codebase, we do use Leanplum and referencing this README https://github.com/mparticle-integrations/mparticle-apple-integration-leanplum it looks like we have to disable AppDelegate proxying.

**Comment by samdozor** [comment]
hey @spencerprescott yep, its their swizzling. We are working on a way to be compatible with it but for now I recommend that you disable our proxy and manually call our UIApplication and UNNotificationCenter APIs as described here: https://docs.mparticle.com/developers/sdk/ios/initialize-the-sdk/#appdelegate-proxy

**Comment by spencerprescott** [comment]
@samdozor thanks, we will disable proxying for now until another solution is available.
