### ISSUE TITLE
How to associate integration instances initialized via their first-party SDK?

### ISSUE THREAD

**Issue by hkellaway** [mParticle/mparticle-apple-sdk#83]
I'm trying to find how to associate a "kit instance" initialized via its own first-party SDK with the mParticle SDK.

For example, instead of instantiating `Appboy` via mParticle, I create an `Appboy` instance using the Appboy (aka Braze) SDK - **how do i tell the mParticle SDK to use that instance?**

in other words, i'd like to replace the following:

```
    [[MParticle sharedInstance] kitInstance:[NSNumber numberWithInteger:MPKitInstanceAppboy]
                          completionHandler:^(id  _Nullable kitInstance) {
        Appboy *appboy = kitInstance;
        if (appboy) {
            ...
        }
    }];
```

with 

```
    [Appboy startWithApiKey:...
              inApplication:self
          withLaunchOptions:launchOptions 
         withAppboyOptions:...];
```

then associate with `MParticle.sharedInstance()` that it should use `Appboy.sharedInstance()` for any Appboy requests

**Comment by hkellaway** [comment]
gotcha - appreciate the quick response

i personally think it would be a good ability - in case the first-party SDKs require special configuration that the mParticle wrapper doesn't keep up with

**Comment by hkellaway** [comment]
incidently - mParticle does naturally use `Appboy.sharedInstance()`.  my concern really is that starting the Appboy isntance via the Appboy SDK with an Appboy API key - then also via the mPaticle SDK with the mParticle key will cross wires & either/both services wont end up with the data they need

**Comment by samdozor** [comment]
I'm curious what the use case is to initialized Braze yourself? Are you seeing an issue with how mParticle initializes?
