### ISSUE TITLE
MPURLRequestBuilder crash

### ISSUE THREAD

**Issue by SebastianThiebaud** [mParticle/mparticle-apple-sdk#84]
Hello,

Just reporting a crash MPURLRequestBuilder.m line 208. You can find attached a crash report for more information. 

This crash has a pretty decent impact in our application. 

[Uploading com.postmates.postmatescourier.enterprise_issue_10805_crash_ca6a0cbabbb542f8afe4fde0a150b85d_DNE_0_v2 (1).txt…]()

**Comment by samdozor** [comment]
hey @SebastianThiebaud ! Thanks for the report. I think your crash report failed to load - are you able to re-upload? 

Can you also please share:
1. SDK version
2. Any steps to reproduce
3. How often this is occurring

If you shoot support@mparticle.com an email we can open a ticket and take it from there as well. Your team has a dedicated slack channel - it may be most expedient to continue the conversation there if you prefer.

**Comment by samdozor** [comment]
Hi @SebastianThiebaud have you had a chance to look more into this? Please provide the additional details above or reach out directly over slack when you have a chance. Thanks!

**Comment by samdozor** [comment]
Hi @SebastianThiebaud we are releasing 7.8.6 today which may resolve this issue. We think this is due to a edge case of low memory devices with a large backlog of uploads to perform.
