### ISSUE TITLE
Enabling group defaults in mParticle overwrites group defaults with standard defaults values

### ISSUE THREAD

**Issue by thuss** [mParticle/mparticle-apple-sdk#86]
We store a lot of values, preferences, and data in general in standard defaults and we noticed all of a sudden all of our standard defaults were showing up in group defaults too. In some cases overwriting our group default values with the value in standard defaults. This was after enabling group defaults on mParticle with `options.sharedGroupID = appGroupName`. 

This code in the mParticle SDK is the cause:

https://github.com/mParticle/mparticle-apple-sdk/blob/master/mParticle-Apple-SDK/Utils/MPIUserDefaults.m#L185-L189

This code isn't safe and needs to be refactored to only copy mParticle defaults keys over. It should not be copying every standard default in the app into a group default. Especially for keys the SDK has nothing to do with.

**Comment by samdozor** [comment]
hey @thuss thanks for the report - we'll resolve this in the next SDK release this week.

**Comment by samdozor** [comment]
Hi @thuss just to give an update here - the fix for this did not make it into today's release but will be incoming ASAP.

**Comment by BrandonStalnaker** [comment]
Hi @thuss the fix for this issue went out in our 7.8.6 release yesterday. Thank you for your patience and for submitting this issue to us.
