### ISSUE TITLE
Build Warning When Compiling Today Extension 

### ISSUE THREAD

**Issue by InteractiveLogic** [mParticle/mparticle-apple-sdk#87]
We recently started using the mParticle SDK in a Today Extension and we are getting the following warning when we build now, whereas we were not previously when we were using it only in our iOS app:

`warning: linking against a dylib which is not safe for use in application extensions:`

I followed the [instructions for using the SDK in an App Extension](https://docs.mparticle.com/developers/sdk/ios/app-extensions/), including the adding the appropriate flag to `Swift Compiler - Custom Flags` in Xcode (I also attempted adding the flags for Objective-C as well since we do have some Obj-C included in the extension, even though most of the codebase in the extension is Swift).

The next bit could be important, however...

As a practice, we do not use CocoaPods or Carthage. We integrate mParticle via a submodule to the Git repo for the latest release commit. So it’s still a framework, but we create a target dependency on that sub-project to integrate it. I didn't know if that would have an impact on the integration with the extension but I thought I'd better mention it.

Additionally, I read the information for issue #39 but it didn't indicate anything for the scenario in which we are using the SDK, so I thought I'd better reach out to see if you had any further insights on how to get that warning to go away.

We are currently using version 7.8.4 of the SDK (commit 62379c0516ee49793007fab6a5f433c40b7906b9)

**Comment by samdozor** [comment]
hey @InteractiveLogic thanks for the report. This definitely seems like it's related to the build setup. We'll see if we can reproduce the warning on our side ASAP.

**Comment by InteractiveLogic** [comment]
Thanks, @samdozor! Much appreciated!

**Comment by BrandonStalnaker** [comment]
@InteractiveLogic Could you tell me a bit more about how you integrate mParticle with submodules. I'm assuming its through Git submodules?

I've been unable to reproduce the warning using Cocoapods or Carthage but I'm still exploring other possibilities.

**Comment by InteractiveLogic** [comment]
Hi @BrandonStalnaker - Yes we use Git submodules, and the project is in a subdirectory of our main project directory. Let me know if you need further details. 

Thanks for looking into it! 👍

**Comment by InteractiveLogic** [comment]
@BrandonStalnaker A team member just informed me that we most likely used this as a guide when integrating the library as a Git submodule:

https://github.com/mParticle/mparticle-apple-sdk/wiki/Manual-installation-instructions

Thanks again!

**Comment by BrandonStalnaker** [comment]
@InteractiveLogic Could you try
1. Go into your version of mParticle-Apple-SDK.xcodeproj (the one in their project directory because of submodules)
2. Go to the Build Settings tab of the mParticle-iOS-SDK target.
3. Set the Require Only App-Extension-Safe API to YES.

thats should get rid of the warning for you.
I'm still looking for a way to correct this on our side but this should unblock you at least. We'll update the Documentation to note the final result.

**Comment by InteractiveLogic** [comment]
@BrandonStalnaker Sure -- we had seen this solution in SO for others who had gotten this warning, and as I recall it did calm the warning down. Having an official solution will be awesome, if possible, but we'll just go ahead and enable that setting in the meantime.

Thanks! 👍

**Comment by InteractiveLogic** [comment]
@BrandonStalnaker Oh just a follow-up question... It sounds like you were able to duplicate the issue on your end, is that correct?

**Comment by BrandonStalnaker** [comment]
@InteractiveLogic Yes I was.

**Comment by InteractiveLogic** [comment]
Cool. We discussed it on our end here and I think what we're going to do for the time being is set that flag in the Extension itself instead of the mParticle project. It seems to have roughly the same effect (quieting the warning down), and we only end up making changes in our project's settings (i.e. we don't have to modify the mParticle project).

But please keep me posted on any new findings or developments on this topic...

Thanks for all your help, @BrandonStalnaker! 👍

**Comment by BrandonStalnaker** [comment]
We decided that the simplest solution and the one used in several other SDKs was to set the Require Only App-Extension-Safe API Flag for our iOS target. That change will be reflected in our next release.
