### ISSUE TITLE
Iterable Kit crash if no webpage URL in continue user activity

### ISSUE THREAD

**Issue by staminajim** [mParticle/mparticle-apple-sdk#88]
Hi, found that the Iterable Kit crashes is continueUserActivity is called, but `userActivity.webpageURL` is nil.

I have a fix over here:

https://github.com/mparticle-integrations/mparticle-apple-integration-iterable/pull/1

(sorry if this is the wrong repo to report the issue in)

**Comment by samdozor** [comment]
Hey @staminajim thanks for the report and the PR! Fix looks pretty straightforward but we'll confirm today.

**Comment by amsalt18** [comment]
Hi @samdozor looks like the fix was merged. Good to close this issue?

**Comment by samdozor** [comment]
Yep all set - this will go out in the next release, which should be tomorrow.
