### ISSUE TITLE
Braze 3.20.0 Integration

### ISSUE THREAD

**Issue by edulpn** [mParticle/mparticle-apple-sdk#92]
Hi, I'm using mParticle integration for Braze and received an email from Braze instructing us to update to version `3.20.0`.
I bumped both `mparticle-apple-sdk` and `mparticle-apple-integration-appboy` to the latest release on Carthage (`7.10.5` and `7.9.1` respectively), the app builds fine, but crashes in runtime:

```
dyld: Symbol not found: _ABKAppboyEndpointDelegateKey
  Referenced from: /Users/eduardo.pinto/Library/Developer/CoreSimulator/Devices/0BCC7105-7378-42ED-A359-73390A6AD7AD/data/Containers/Bundle/Application/4A407BF5-22C0-44C1-8CB3-CBEA670F2E52/AMARO Hybris Dev.app/Frameworks/mParticle_Appboy.framework/mParticle_Appboy
  Expected in: /Users/eduardo.pinto/Library/Developer/CoreSimulator/Devices/0BCC7105-7378-42ED-A359-73390A6AD7AD/data/Containers/Bundle/Application/4A407BF5-22C0-44C1-8CB3-CBEA670F2E52/AMARO Hybris Dev.app/Frameworks/Appboy_iOS_SDK.framework/Appboy_iOS_SDK
 in /Users/eduardo.pinto/Library/Developer/CoreSimulator/Devices/0BCC7105-7378-42ED-A359-73390A6AD7AD/data/Containers/Bundle/Application/4A407BF5-22C0-44C1-8CB3-CBEA670F2E52/AMARO Hybris Dev.app/Frameworks/mParticle_Appboy.framework/mParticle_Appboy
```

This leads me to think the integrations are still not released. I saw the tag `7.10.6` on `mparticle-apple-integration-appboy`, but I'm not being able to reference it on Carthage, since there is no pre-build framework on it and it fails when trying to build it from source.

What's the status on this? 
Thanks!

**Comment by samdozor** [comment]
hey @edulpn we have stopped shipping binaries for individual kits (we still ship it for core) since they're typically only a couple source files to compile. That said - you should be able to compile 7.10.6 of `mparticle-apple-integration-appboy` - can you share the compilation issue that you're having?

**Comment by edulpn** [comment]
```
*** Fetching mparticle-apple-sdk
*** Fetching appboy-ios-sdk
*** Checking out mparticle-apple-sdk at "7.10.5"
*** Checking out mparticle-apple-integration-appboy at "7.10.6"
*** Checking out appboy-ios-sdk at "3.20.1"
*** xcodebuild output can be found in /var/folders/0t/4lpgbc8x09d3cm540qq49kpc38kfsx/T/carthage-xcodebuild.wV6ElL.log
*** Downloading mparticle-apple-sdk.framework binary at "Version 7.10.5"
*** Downloading appboy-ios-sdk.framework binary at "3.20.1"
*** Building scheme "mParticle-Appboy" in mParticle-Appboy.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/eduardo.pinto/dev/ios-workspace/iamaro/Carthage/Checkouts/mparticle-apple-integration-appboy/mParticle-Appboy.xcodeproj -scheme mParticle-Appboy -configuration Release -derivedDataPath /Users/eduardo.pinto/Library/Caches/org.carthage.CarthageKit/DerivedData/10.1_10B61/mparticle-apple-integration-appboy/7.10.6 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/0t/4lpgbc8x09d3cm540qq49kpc38kfsx/T/mparticle-apple-integration-appboy SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/eduardo.pinto/dev/ios-workspace/iamaro/Carthage/Checkouts/mparticle-apple-integration-appboy)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/0t/4lpgbc8x09d3cm540qq49kpc38kfsx/T/carthage-xcodebuild.wV6ElL.log
```

Do you need a complete log?

**Comment by samdozor** [comment]
hey @edulpn it looks like you're using xcode 10.1 - is that right? I see that Braze no longer supports Xcode 10.1: https://github.com/Appboy/appboy-ios-sdk/issues/199

Could you try using Xcode 10.3 or later?

**Comment by samdozor** [comment]
hey @edulpn yes unfortunately that's my understanding of the impact. Both Braze and mParticle will be unable to register for push on iOS 13 (or more specifically, the push tokens will be unusable), unless you upgrade both SDKs.

Braze has an outstanding issue in their repo for this bitcode problem and have stated they will not be back-supporting old Xcode 10.1 for iOS 13: https://github.com/Appboy/appboy-ios-sdk/issues/199

In the short term, you could build a custom version of both mParticle and Braze based on older versions of the SDKs and ship those SDKs together with your app.

The changes you would need are here:
mParticle commit: https://github.com/mParticle/mparticle-apple-sdk/commit/57fb1f23752eb0cfa98b5c74b7256cc4d36bf856

The Braze issue linked above details what you'd need to change there.

**Comment by edulpn** [comment]
hey @samdozor sorry for the delay, I've been having carthage hell for the last couple of days... yeah, I've been bumping stuff (Swift and libs).
I'm at the point everything compiles (including `mparticle-apple-sdk`) but I'm having issues with the Appboy integration kit. `appboy-ios-sdk` won't accept `--no-use-binaries` (it doesn't have a shared scheme for building) and will take ages to clone/fetch/download the prebuilt binary and after that `mparticle-apple-integration-appboy` fails building. The log says it's on `#import <Appboy_iOS_SDK/Appboy-iOS-SDK-umbrella.h>`, it can't find it a couple of times.

Any ideas? All of this is building on Xcode 10.3 and your libs are on version `7.11.0`

**Comment by edulpn** [comment]
Also, let me know if you want to take a look on the complete log files

**Comment by edulpn** [comment]
After some wiggling around, I added `appboy-ios-sdk ~> 3.20` to my project Cartfile and it worked (I guess because the integration kit points out to my project Carthage build folder). Is this an issue, that the integration kit can't download it's own Appboy SDK?
