### ISSUE TITLE
Support for WatchOS

### ISSUE THREAD

**Issue by JoeySlomowitz** [mParticle/mparticle-apple-sdk#94]
Currently, the only available approach to send events from WatchOS is through the `WatchConnectivity` framework Apple provides.  However, this relies on an iOS companion app to then log that event through MParticle.

Apple has now provided the ability to create a watch only app, and also recommends existing apps (with an iOS companion) to make the experience fully independent.

> Apple Watch users have come to expect that the apps on their watches just work, even when they don’t have their iPhones with them. To ensure the best experience for all Apple Watch users, create an independent watchOS app that doesn’t require an iOS companion.

https://developer.apple.com/documentation/watchkit/creating_independent_watchos_apps

**Comment by samdozor** [comment]
hey @JoeySlomowitz! this is definitely on our roadmap but I unfortunately to not have an exact date for you at this time.
