### ISSUE TITLE
All MPEventType enums are now broken

### ISSUE THREAD

**Issue by eseay** [mParticle/mparticle-apple-sdk#96]
After updating to version 7.12.0 (from 7.11.0), a change to the `MPEnums.h` file to swap the event type enum from being an `NS_ENUM` to an `enum` has broken all my existing references to `MPEventType`.

Effectively, anywhere I had used a Swift type-referenced event type, such as `.navigation`, I am now getting a compiler error and must swap it to use `MPEventTypeNavigation`

**Comment by BrandonStalnaker** [comment]
@eseay We've released [7.12.1](https://github.com/mParticle/mparticle-apple-sdk/releases/tag/7.12.1) to restore your previous functionality. 

Thanks again for calling this out and let us know if we could help in any other way.

**Comment by eseay** [comment]
@BrandonStalnaker Thanks for the quick resolution!
